version: '3.3'

services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=freestyle_jury
    ports:
      - "127.0.0.1:27017:27017/tcp"
  app:
    build: .
    env_file:
      - dev_variables.env
    stdin_open: true
    tty: true
    ports:
      - "127.0.0.1:8007:8765/tcp"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    links:
      - mongodb
