name: Test, build and deploy to prod
on:
  schedule:
    - cron: '0 1,7,13,19 * * *'
jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      OS: 'ubuntu-latest'
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    - name: Get commit count
      run: |
        export COMMIT_COUNT=$(git rev-list --since="6 hours" --count master)
        if (( $COMMIT_COUNT > 0 )); then
        echo "::set-env name=HAS_CHANGES::true"
        echo "There are changes, deployiong to prod..."
        else
        echo "::set-env name=HAS_CHANGES::false"
        echo "There are no changes, skiping execution"
        fi
    # TEST
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      if: env.HAS_CHANGES
      with:
        python-version: '3.8'
    - name: Install dependencies
      if: env.HAS_CHANGES
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Unit Test
      if: env.HAS_CHANGES
      run: |
        pytest test/unit --cov=./ --cov-report=xml
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    - name: Integration Test
      if: env.HAS_CHANGES
      run: |
        pytest test/integration
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
    #DEPLOY
    - name: Get Previous tag
      if: env.HAS_CHANGES
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@master"
    - name: Deploy to Dockerhub
      if: env.HAS_CHANGES
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: matisotee/freestyle-jury-api
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ steps.previoustag.outputs.tag }}"
