name: Test
on:
  pull_request:
    branches:
      - master
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    # TEST
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Unit Test
      run: |
        coverage run --source='.' ./manage.py test test/unit
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        github-token: ${{ secrets.COVERALLS_REPO }}
        parallel: true
    - name: Integration Test
      run: |
        coverage run --source='.' ./manage.py test test/integration
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

  Coveralls_finish:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          github-token: ${{ secrets.COVERALLS_REPO }}
          parallel-finished: true
