name: Test
on:
  pull_request:
    branches:
      - master
jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      OS: 'ubuntu-latest'
      PYTHON: '3.8'
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    # TEST
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Linting
      run: |
        flake8
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    - name: Unit Test
      run: |
        pytest test/unit --cov=./ --cov-report=xml
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    - name: Coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
    - name: Integration Test
      run: |
        pytest test/integration
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
