name: Test
on:
  pull_request:
    branches:
      - master
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '0'
    # TEST
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Unit Test
      run: |
        coverage run --source='.' ./manage.py test test/unit
        coveralls
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO }}
    - name: Integration Test
      run: |
        coverage run --source='.' ./manage.py test test/integration
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
